@hostname = http://localhost:4000
@port = 3000
@host = https://rocky-temple-86195.herokuapp.com

###The requests ####

### app endpoint check ###w
GET {{host}} HTTP/1.1

### wallet functionality ###
GET {{host}}/wallet HTTP/1.1

### wallet functionality - create wallet ###
GET  {{host}}/wallet/create HTTP/1.1

### wallet functionality - create account ###
GET {{host}}/wallet/account HTTP/1.1
### wallet functionality - get balance ###
POST {{host}}/wallet/balance HTTP/1.1
Content-Type: application/json

{
    "address": "0xcdC1256d189dd9C435a52E6fa39afE18CAC23A1C"
}
### import account functionality ###
GET {{host}}/import HTTP/1.1

### import account functionality -import  ###
POST {{host}}/import/account HTTP/1.1
Content-Type: application/json

{
    "privateKey": "0xd4a66f4bff4030a27f4cea0867a12f9cff8a2cfed4447645495fffe6cc3550ff"
}

### conduct transaction ###
GET {{host}}/transaction HTTP/1.1

### conduct transaction ###
POST {{hostname}}/transaction/send HTTP/1.1
Content-Type: application/json

{
    "privateKey":"0x69807e904829dbe07d7ac855d62875baac02421f1f1ec0f4f3fd32b73e5f6d08",
    "to":"0x81031fc7093C904E106B1782DC433cA2e33e55A0",
    "from":"0x0A946DD7b8ff2d193C17081a6aB82Db0BfB2888F",
    "value":"12000000000"
}